server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unified_banking_auth
    username: unibank_admin
    password: UniBank@Local123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


app:
  jwt:
    secret: "ThisIsATemporaryLocalDevSecretKeyChangeMeLater123456"
    expiration-ms: 3600000