server:
  port: 8084

spring:
  application:
    name: consent-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unified_banking_consent
    username: unibank_admin
    password: UniBank@Local123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true